"""empty message

Revision ID: 125403bc7356
Revises: c32009f7bea9
Create Date: 2022-08-01 22:41:56.040422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125403bc7356'
down_revision = 'c32009f7bea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
